Traceback (most recent call last):
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 229, in run
    self.play_game(challenge=challenge)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 193, in play_game
    gamestate = self.create_initial_gamestate()
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 79, in create_initial_gamestate
    moveset = SmogonMoveset(None, None, None, None, {'hp': 88, 'patk': 84, 'pdef': 84, 'spatk': 84, 'spdef': 84, 'spe': 84}, {'hp': 1.0, 'patk': 1.0, 'pdef': 1.0, 'spatk': 1.0, 'spdef': 1.0, 'spe': 1.0}, None, 'ou')
TypeError: __init__() takes exactly 8 arguments (9 given)
