Traceback (most recent call last):
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 225, in run
    self.play_game(challenge=challenge)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 189, in play_game
    gamestate = self.create_initial_gamestate()
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 81, in create_initial_gamestate
    moves = [x[0] for x in poke.predict_moves([])]
  File "/home/vasu/Work/pokemon_ai/showdown_ai/team.py", line 171, in predict_moves
    return self.predictor(known_moves)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/move_predict.py", line 14, in __call__
    return self.get_moves(*args)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/move_predict.py", line 40, in get_moves
    probs = self.get_freqs(poke, self.freq)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/move_predict.py", line 67, in get_freqs
    total = float(sum(freq[poke].values()))
KeyError: 'Keldeo-Resolute'
