Traceback (most recent call last):
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 241, in run
    self.play_game(challenge=challenge)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/showdown.py", line 204, in play_game
    self.selenium.switch_initial(0, 0)
  File "/home/vasu/Work/pokemon_ai/showdown_ai/browser.py", line 196, in switch_initial
    self.wait_for_move()
  File "/home/vasu/Work/pokemon_ai/showdown_ai/browser.py", line 309, in wait_for_move
    move_exists = self.check_exists_by_xpath("/html/body/div[4]/div[5]/div/div[2]/div[2]/button[1]")
  File "/home/vasu/Work/pokemon_ai/showdown_ai/browser.py", line 255, in check_exists_by_xpath
    self.driver.find_element_by_xpath(xpath)
  File "/home/vasu/Work/pokemon_ai/venv/local/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 230, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/vasu/Work/pokemon_ai/venv/local/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 662, in find_element
    {'using': by, 'value': value})['value']
  File "/home/vasu/Work/pokemon_ai/venv/local/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 173, in execute
    self.error_handler.check_response(response)
  File "/home/vasu/Work/pokemon_ai/venv/local/lib/python2.7/site-packages/selenium-2.44.0-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 166, in check_response
    raise exception_class(message, screen, stacktrace)
TimeoutException: Message: timeout: Timed out receiving message from renderer: 298.504
  (Session info: chrome=40.0.2214.94)
  (Driver info: chromedriver=2.9.248304,platform=Linux 3.16.0-29-generic x86_64)

